"""Questions the evidence graph is placed to ask, with the evidence named.

`graph_analysis` finds communities, hubs and bridges over the recorded
concept topology, and the evidence graph itself carries typed links
between claims (`contradicts`, `superseded_by`) and chunk-to-concept
mentions. All of that was reported as ids and counts and left to the
reader. A graph that holds a contradiction, a replacement, a cut edge
between two structures, an unlinked concept beside linked ones, or two
names that recur together with nothing recorded between them is placed
to ask something a person would not think to -- and to say which edge
or node made it ask.

Every question names its evidence. None is generated by a model, none is
asserted as a fact, the result is bounded and says when it was cut, and
the analysis's own status travels beside it so an absent question is
never read as an absent shape.
"""

from __future__ import annotations

from copy import deepcopy
import random

from scone_memory.retrieval.evidence_graph import EvidenceEdge, EvidenceNode, QueryEvidenceGraph
from scone_memory.retrieval.graph_analysis import GraphAnalysisResult, analyze_evidence_graph
from scone_memory.retrieval.graph_questions import MAX_QUESTIONS, questions_for

KINDS = {"contradiction", "replacement", "lone_bridge", "isolated", "co_mention"}


def concept(identifier: str) -> EvidenceNode:
    return EvidenceNode(id=identifier, kind="concept", label=identifier.upper())


def claim(number: int, label: str, ts: str | None = None) -> EvidenceNode:
    return EvidenceNode(id=f"claim:{number}", kind="claim", label=label, ts=ts, data={"fact_id": number})


def chunk(number: int) -> EvidenceNode:
    return EvidenceNode(id=f"chunk:{number}", kind="chunk", label="a passage")


def recorded(left: str, right: str, number: int) -> EvidenceEdge:
    """The shape the analysis admits as a recorded relation between concepts."""
    return EvidenceEdge(source=left, target=right, kind="relation", label="works with",
                        data={"category": "fact_relation", "fact_id": number, "source_episode_id": number,
                              "quote": "retained quote", "origin": "stated", "provenance_status": "retained"})


def link(left: int, right: int, kind: str, status: str = "retained") -> EvidenceEdge:
    """A stored typed link between two claims, as the evidence graph projects it."""
    return EvidenceEdge(source=f"claim:{left}", target=f"claim:{right}", kind=kind, label=kind.replace("_", " "),
                        data={"category": "fact_relation", "link_id": left * 100 + right, "provenance_status": status})


def superseded(old: int, new: int) -> EvidenceEdge:
    return EvidenceEdge(source=f"claim:{old}", target=f"claim:{new}", kind="superseded_by", label="Superseded by",
                        data={"category": "fact_relation", "provenance_status": "unstated"})


def mention(chunk_number: int, concept_id: str) -> EvidenceEdge:
    return EvidenceEdge(source=f"chunk:{chunk_number}", target=concept_id, kind="mentions",
                        label="Mentions a recorded name", data={"category": "mention"})


def build(nodes, edges, **fields) -> QueryEvidenceGraph:
    return QueryEvidenceGraph(nodes=list(nodes), edges=list(edges), **fields)


def ask(graph: QueryEvidenceGraph):
    return questions_for(graph, analyze_evidence_graph(graph))


def of_type(found, kind: str):
    return [q for q in found.questions if q.type == kind]


def triangles_joined_once() -> QueryEvidenceGraph:
    return build([concept(n) for n in "abcxyz"],
                 [recorded("a", "b", 1), recorded("b", "c", 2), recorded("c", "a", 3),
                  recorded("x", "y", 4), recorded("y", "z", 5), recorded("z", "x", 6), recorded("c", "x", 7)])


def test_a_contradiction_asks_which_side_holds():
    g = build([claim(1, "sky is blue"), claim(2, "sky is green")], [link(1, 2, "contradicts")])
    asked = of_type(ask(g), "contradiction")
    assert len(asked) == 1
    assert "sky is blue" in asked[0].question and "sky is green" in asked[0].question
    assert asked[0].evidence == {"edge_kind": "contradicts", "source": "claim:1", "target": "claim:2",
                                 "provenance_status": "retained"}


def test_a_contradiction_whose_own_evidence_is_gone_says_so():
    g = build([claim(1, "a"), claim(2, "b")], [link(1, 2, "contradicts", status="missing")])
    asked = of_type(ask(g), "contradiction")
    assert asked[0].evidence["provenance_status"] == "missing"
    assert "missing" in asked[0].why


def test_a_replacement_asks_what_changed_and_when():
    g = build([claim(1, "price is 5", ts="2026-01-01T00:00:00Z"), claim(2, "price is 6", ts="2026-02-01T00:00:00Z")],
              [superseded(1, 2)])
    asked = of_type(ask(g), "replacement")
    assert len(asked) == 1
    assert "price is 5" in asked[0].question and "price is 6" in asked[0].question
    assert asked[0].evidence == {"edge_kind": "superseded_by", "source": "claim:1", "target": "claim:2",
                                 "since": "2026-02-01T00:00:00Z"}


def test_a_co_mention_without_a_recorded_relation_asks_what_the_link_is():
    g = build([concept("a"), concept("b"), chunk(1)], [mention(1, "a"), mention(1, "b")])
    asked = of_type(ask(g), "co_mention")
    assert len(asked) == 1
    assert asked[0].evidence == {"concepts": ["a", "b"], "chunks": ["chunk:1"], "chunk_count": 1}


def test_a_co_mention_with_a_recorded_relation_asks_nothing():
    g = build([concept("a"), concept("b"), chunk(1)], [mention(1, "a"), mention(1, "b"), recorded("a", "b", 1)])
    assert of_type(ask(g), "co_mention") == []


def test_co_mentions_are_ranked_by_how_often_they_recur():
    g = build([concept("a"), concept("b"), concept("c"), chunk(1), chunk(2)],
              [mention(1, "a"), mention(1, "b"), mention(1, "c"), mention(2, "b"), mention(2, "c")])
    asked = of_type(ask(g), "co_mention")
    assert [q.evidence["concepts"] for q in asked] == [["b", "c"], ["a", "b"], ["a", "c"]]
    assert asked[0].evidence["chunk_count"] == 2 and asked[0].evidence["chunks"] == ["chunk:1", "chunk:2"]


def test_a_cut_edge_between_two_structures_asks_what_else_connects_them():
    g = triangles_joined_once()
    analysis = analyze_evidence_graph(g)
    assert [(b.source, b.target, b.cut_edge) for b in analysis.bridges] == [("c", "x", True)]
    asked = of_type(questions_for(g, analysis), "lone_bridge")
    assert len(asked) == 1
    assert asked[0].evidence == {"source": "c", "target": "x", "relation_count": 1}


def test_a_pendant_edge_is_not_a_lone_bridge():
    """A leaf's one edge is trivially the only link to it. No separate rule
    is needed: a leaf always takes its neighbour's community label, so its
    edge is never cross-community. This pins that the cross-community rule
    keeps covering it."""
    g = build([concept(n) for n in "abcd"],
              [recorded("a", "b", 1), recorded("b", "c", 2), recorded("c", "a", 3), recorded("c", "d", 4)])
    analysis = analyze_evidence_graph(g)
    assert any(b.cut_edge for b in analysis.bridges)
    assert of_type(questions_for(g, analysis), "lone_bridge") == []


def test_an_unlinked_concept_beside_linked_ones_asks_whether_it_is_unread():
    g = build([concept("a"), concept("b"), concept("lonely")], [recorded("a", "b", 1)])
    asked = of_type(ask(g), "isolated")
    assert len(asked) == 1
    assert asked[0].evidence == {"node_ids": ["lonely"], "linked_concepts": 2}


def test_no_topology_at_all_asks_nothing_about_isolation():
    """When nothing is linked every concept is unlinked, and asking about all
    of them is not asking. That disclosure is the analysis's (`method ==
    'unlinked'`), carried beside the questions, not turned into one."""
    found = ask(build([concept("a"), concept("b")], []))
    assert of_type(found, "isolated") == []
    assert found.analysis_method == "unlinked"


def test_a_supported_recorded_relation_asks_nothing():
    """The other half: a supported link and a recorded relation are what
    the graph is for, and a generator that always asks is not asking."""
    g = build([claim(1, "a"), claim(2, "b"), concept("a"), concept("b")],
              [link(1, 2, "supports"), recorded("a", "b", 1)])
    assert ask(g).questions == []


def test_questions_are_bounded_and_say_so():
    count = MAX_QUESTIONS + 20
    g = build([claim(i, f"claim {i}") for i in range(count + 1)], [link(i, i + 1, "contradicts") for i in range(count)])
    found = ask(g)
    assert len(found.questions) == MAX_QUESTIONS
    assert found.omitted == count - MAX_QUESTIONS and found.truncated is True


def test_the_weakest_questions_are_cut_first():
    """Co-mentions can multiply (one passage naming ten things makes 45
    pairs); they rank last so the bound never cuts a contradiction to
    keep one."""
    names = [f"n{i}" for i in range(MAX_QUESTIONS)]
    g = build([claim(1, "a"), claim(2, "b"), chunk(1), *[concept(n) for n in names]],
              [link(1, 2, "contradicts"), *[mention(1, n) for n in names]])
    found = ask(g)
    assert found.truncated and found.questions[0].type == "contradiction"
    assert all(q.type == "co_mention" for q in found.questions[1:])
    pairs = MAX_QUESTIONS * (MAX_QUESTIONS - 1) // 2
    assert len(found.questions) == MAX_QUESTIONS and found.omitted == pairs - (MAX_QUESTIONS - 1)


def test_an_unavailable_analysis_yields_no_questions_and_says_why():
    found = questions_for(build([concept("a")], []), GraphAnalysisResult.unavailable("no_topology"))
    assert found.questions == [] and found.truncated is False
    assert found.analysis_status == "unavailable" and found.reason == "no_topology"


def test_a_partial_analysis_is_disclosed_beside_the_questions():
    found = ask(build([concept("a"), concept("b")], [recorded("a", "b", 1)], truncated=True))
    assert found.analysis_status == "partial" and found.reason is None


def test_every_question_is_a_question_and_names_its_evidence():
    g = build([claim(1, "one"), claim(2, "two"), claim(3, "three"), chunk(1), *[concept(n) for n in "abcxyz"], concept("lonely")],
              [link(1, 2, "contradicts"), superseded(2, 3), mention(1, "lonely"), mention(1, "a"),
               *triangles_joined_once().edges])
    found = ask(g)
    assert {q.type for q in found.questions} == KINDS
    for q in found.questions:
        assert q.question.endswith("?")
        assert q.why and q.evidence


def test_questions_do_not_depend_on_input_order():
    g = build([claim(1, "one"), claim(2, "two"), claim(3, "three"), chunk(1), chunk(2), *[concept(n) for n in "abcxyz"], concept("lonely")],
              [link(1, 2, "contradicts"), superseded(2, 3), mention(1, "lonely"), mention(1, "a"), mention(2, "a"), mention(2, "lonely"),
               *triangles_joined_once().edges])
    expected = ask(g)
    assert expected.questions
    for seed in range(5):
        copied = deepcopy(g)
        random.Random(seed).shuffle(copied.nodes)
        random.Random(seed + 1).shuffle(copied.edges)
        assert ask(copied) == expected


def test_a_long_label_is_shortened_in_the_question_but_exact_in_the_evidence():
    """The analysis never copies text; a question must, to be readable, but
    bounded. The evidence ids stay exact so nothing is lost."""
    from scone_memory.retrieval.graph_questions import MAX_LABEL_CHARS

    long = "x" * (MAX_LABEL_CHARS * 3)
    g = build([EvidenceNode(id="claim:1", kind="claim", label=long), claim(2, "short")], [link(1, 2, "contradicts")])
    asked = of_type(ask(g), "contradiction")[0]
    assert "x" * MAX_LABEL_CHARS not in asked.question
    assert "x" * (MAX_LABEL_CHARS - 1) + "…" in asked.question
    assert asked.evidence["source"] == "claim:1"


def test_a_cut_edge_inside_a_tree_is_not_a_lone_bridge():
    """A query-scoped graph of a few facts is nearly always a forest, and in
    a forest every internal edge is a cut edge. Asking "is this really the
    only link" about each would fire on almost every query for no reason.
    Measured on this package's source: 23 such questions over 24 queries,
    all of them trivial. A lone bridge is one that joins two structures the
    analysis found -- communities, which need cycles to exist."""
    g = build([concept(n) for n in "abcd"], [recorded("a", "b", 1), recorded("b", "c", 2), recorded("c", "d", 3)])
    analysis = analyze_evidence_graph(g)
    assert analysis.method == "components"
    assert [(b.source, b.target, b.cut_edge, b.pendant) for b in analysis.bridges] == [("a", "b", True, True), ("b", "c", True, False), ("c", "d", True, True)]
    assert of_type(questions_for(g, analysis), "lone_bridge") == []


def test_two_communities_joined_twice_have_no_lone_bridge():
    """Cross-community is not enough on its own: two triangles joined by two
    edges have cross-community bridges, and neither is the only link."""
    g = build([concept(n) for n in "abcxyz"],
              [recorded("a", "b", 1), recorded("b", "c", 2), recorded("c", "a", 3),
               recorded("x", "y", 4), recorded("y", "z", 5), recorded("z", "x", 6),
               recorded("c", "x", 7), recorded("b", "y", 8)])
    analysis = analyze_evidence_graph(g)
    crossing = [b for b in analysis.bridges if b.cross_community]
    assert crossing and not any(b.cut_edge for b in crossing), analysis.bridges
    assert of_type(questions_for(g, analysis), "lone_bridge") == []
